Feature/language changes
Los-CeeSharpos-Hermanos/skill-matrix pull request #57
Opened 2021-10-14 06:35 UTC by NWisotzki

#32 solved (maybe with bugs)

2021-10-14 07:25 UTC, conradoalexsander requested changes
It looks like the edit feature is with an strange behavior. I left a comment on code about that. 

PS.: The size of the columns on list view, seems to be varying depending on its content, the skills list view has a similar problem. I am trying to fix it too.

2021-10-14 07:25 UTC, conradoalexsander commented on web/src/app/admin/languages/add-language.component.ts
> +        for(let language of this.languages) {
I think you might don't need to validate the id nor the language handle its generation. The generation of the id will be done in the backend, the mock app auto generate this as well. 
```suggestion
        for(let language of this.languages) {
```

2021-10-14 07:25 UTC, conradoalexsander commented on web/src/app/admin/languages/add-language.component.ts
> +              this.snackBarService.warn('Please fill every field');
Here, you can move all the validation to form control. So it will block invalid forms to be submitted.

2021-10-15 07:39 UTC, EneOne approved these changes

2021-10-15 07:41 UTC, merged